[oidc]
base_external_id = "http://localhost:8000"

[oidc.providers.dev]
issuer = "http://oidc-mock:9400"
client_id = "dev-client"
client_secret = "dev-secret" # Should be stored in an environmant variable in prod.
scopes = ["openid", "profile", "email"]
