services:
  postgres:
    image: docker.io/library/postgres:18
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dionysus_db
    volumes:
      - pgdata:/var/lib/postgresql
  dionysus:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/dionysus_db
    depends_on:
      - postgres

volumes:
  pgdata:
