services:
  postgres:
    image: docker.io/library/postgres:18
    container_name: local-postgres
    environment:
      POSTGRES_USER: dionysus
      POSTGRES_PASSWORD: dionysus
      POSTGRES_DB: dionysus
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dionysus"]
      interval: 5s
      timeout: 3s
      retries: 10

  oidc-mock:
    image: ghcr.io/geigerzaehler/oidc-provider-mock:latest
    container_name: local-oidc-mock
    ports:
      - "127.0.0.1:9400:9400"
    healthcheck:
      test: [
        "CMD-SHELL",
        "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:9400/.well-known/openid-configuration').read()\""
      ]
      # test: ["CMD", "wget", "-qO-", "http://localhost:9400/.well-known/openid-configuration"]
      interval: 5s
      timeout: 3s
      retries: 10

  dionysus:
    build:
      context: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./backend/config/dev.toml:/etc/dionysus/config.toml:ro
    environment:
      - DIONYSUS_DATABASE__URL=postgres://dionysus:dionysus@postgres:5432/dionysus
    depends_on:
      postgres:
        condition: service_healthy
      oidc-mock:
        condition: service_healthy

volumes:
  pgdata:
