services:
  postgres:
    image: docker.io/library/postgres:18
    container_name: local-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql
  dionysus:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DIONYSUS_DATABASE__URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    depends_on:
      - postgres

volumes:
  pgdata:
