[package]
name = "backend"
version = "0.1.0"
authors = ["Fredrik Blomqvist", "Emil Hultcrantz"]
edition = "2024"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
axum = "0.8"
yrs-axum = "0.8.2"
tower-http = "0.6.8"
futures-util = "0.3.31"
yrs = "=0.18.8"
